# Generated by Django 6.0.4 on 2026-05-02 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_alter_producto_options_producto_mostrar_cuotas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('Mueble', 'Muebles'), ('Colchon', 'Colchones y Sommier'), ('Living', 'Living'), ('Cocina', 'Cocina'), ('Respaldar', 'Respaldares')], max_length=50, verbose_name='Categoría'),
        ),
    ]
