# Generated by Django 6.0.4 on 2026-05-02 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0005_alter_producto_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('Mueble', 'Muebles'), ('Colchon', 'Colchones y Sommier'), ('Living', 'Living'), ('Cocina', 'Cocina'), ('Respaldar', 'Respaldares'), ('Almohadas', 'Almohadas')], max_length=50, verbose_name='Categoría'),
        ),
    ]
