# Generated by Django 6.0.4 on 2026-05-08 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0006_alter_producto_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='tipo_colchon',
            field=models.CharField(blank=True, choices=[('', 'No aplica'), ('Espuma', 'Espuma'), ('Resorte', 'Resorte')], default='', max_length=20, verbose_name='Tipo de colchón'),
        ),
    ]
