# Generated by Django 6.0.4 on 2026-06-04 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0007_producto_tipo_colchon'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen_2',
            field=models.ImageField(blank=True, null=True, upload_to='productos/', verbose_name='Imagen 2'),
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen_3',
            field=models.ImageField(blank=True, null=True, upload_to='productos/', verbose_name='Imagen 3'),
        ),
    ]
